# Use the official Golang image as the base image
FROM golang:1.13.4

# Set the working directory
WORKDIR /go/src/github.com/edmundtetteh/movies-loader

# Set the environment variable for Go modules
ENV GOCACHE /tmp

# Install golint
RUN go get -u golang.org/x/lint/golint

# Switch back to the original working directory
WORKDIR /go/src/github.com/edmundtetteh/movies-parser

# Copy the source code into the container
COPY . .

# Run go get to fetch the dependencies
RUN go get -v ./...

# Your other Dockerfile commands go here
# ...
