FROM golang:1.16

ENV VERSION v1.0.45
ENV GOCACHE /tmp
WORKDIR /go/src/github/edmundtetteh/movies-parser

RUN curl -o /usr/local/bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-darwin.amd64-$VERSION && \
    chmod +x /usr/local/bin/nancy

RUN go get -u golang.org/x/lint/golint

COPY . .

RUN go get -v 


